- src/hooks/index.tsx
- src/navigation/components/NavigationProvider/index.tsx
- src/navigation/hooks/index.tsx
- src/navigation/hooks/useResize.tsx
Partial of https://linear.app/tt-nyhetsbyran/issue/ELE-183/views-in-the-app-should-be-addedremoved-when-window-size-changes
In this:
* Add `useResize` to be able to register resize
* Remove if view doesn't fit new size
To be able to add a view after resize to bigger viewport we need to have a discussion about how. Might be a weird pattern if we readd views that have been removed?
And we need to set a overall strategy for `min-width` and `max-width` for views.
> feat: remove view that dont fit

- package-lock.json
- package.json
- postcss.config.js
- src/components/PlanningTable/Columns/Actions.tsx
- src/components/PlanningTable/Columns/Assignees.tsx
- src/components/PlanningTable/Columns/Section.tsx
- src/components/PlanningTable/Columns/Title.tsx
- tsconfig.json
- vite.config.ts
Fixes: ELE-252
Use with: https://github.com/ttab/elephant-ui/pull/15
> fix: fonts sizes and weights

- src-srv/index.ts
- src-srv/utils/CollaborationServer.ts
Previous connection works locally since it fallbacks to localhost:6379. But doesn't work when deployed.
Trying what we had initially.
> fix: regression in redis connection string

- src/components/Link/lib/handleLink.ts
- src/views/PlanningOverview/PlanningTable/Columns/Title.tsx
- src/views/PlanningOverview/PlanningTable/Columns/index.tsx
- src/views/PlanningOverview/PlanningTable/index.tsx
We this gets more urgent to fix with this change:
https://linear.app/tt-nyhetsbyran/issue/ELE-332/clicking-on-actions-on-inactive-view-does-not-work-sometimes
> fix: clickable row instead of link

- src/components/ui/ComboBox.tsx
- src/defaults/documentStatuses.tsx
Due to the fact that lucide doesn't have filled icons we can not reproduce the filled circle published sketch (to my knowledge) using lucide. I've adjusted the color according to the sketches.
> fix: published color

- .env.tpl
- src-srv/utils/authConfig.ts
A configurable hint value makes it possible to skip the Keycloak login dialog and go directly to the Identity Provider
> Add kc_idp_hint to authorization URL

- package-lock.json
- package.json
- src/components/DataItem/SluglineEditable.tsx
- src/components/ui/TextBox.tsx
- src/hooks/useDocumentStatus.tsx
- src/views/Planning/components/PlanDocumentStatus.tsx
- src/views/Planning/index.tsx
Tab order for slugline in planning was not working when switching between button and text input. Removed the button and restyled the context of the input to mimick previous behaviour. We should not allow changing slugline on usable planning.
Also added useDocumentStatus() hook that allows both getting and setting the document status much easier.
> Slugline tab order, improved documentStatus handling

- src/components/Header/Datechanger.tsx
- src/views/EventsOverview/EventsHeader/index.tsx
- src/views/PlanningOverview/PlanningHeader/index.tsx
- Added a `type` prop to the `DateChanger` component to make it more flexible.
- Updated the `DateChanger` usage in `EventsHeader` and `PlanningHeader` to pass the appropriate type.
- Modified the `changeDate` function calls to use the `type` prop.
> feat: add type prop to DateChanger component

- src/components/View/ViewHeader/CreateDocumentDialog.tsx
- src/lib/createYItem.ts
- src/views/Event/components/PlanningTable.tsx
- Added `createdDocumentIdRef` prop to `CreateDocumentDialog` component.
- Updated `createDocument` function to set `documentId` to the ref.
- Modified `PlanningTable` to pass `createdDocumentIdRef` to the dialog.
> feat: add createdDocumentIdRef to CreateDocumentDialog

- src/components/Table/NewItems/List.tsx
- src/components/Table/NewItems/Table.tsx
Use a BASE_URL constant instead of directly accessing process.env.BASE_URL in fetch requests. Make sure it doesn't return undefined.
> fix: use BASE_URL constant for API fetch requests

- src/components/Byline.tsx
- src/components/DataItem/SluglineEditable.tsx
- src/components/Form/Content.tsx
- src/components/Form/Group.tsx
- src/components/Form/Root.tsx
- src/components/Section.tsx
- src/components/Title.tsx
- src/components/Validation.tsx
- src/views/Flash/FlashViewContent.tsx
Added validateStateRef prop to various form components to manage validation state references. This change ensures that validation states are properly tracked and cleaned up when components unmount.
> feat: add validateStateRef prop to form components

- src/components/Table/GroupedRows.tsx
- src/components/Table/Rows.tsx
- src/components/Table/index.tsx
- src/contexts/TableProvider.tsx
- src/views/Assignments/AssignmentsList.tsx
- src/views/EventsOverview/EventsList.tsx
- src/views/PlanningOverview/PlanningList.tsx
- Introduced `GroupedRows` and `Rows` components to handle grouped and non-grouped rows respectively.
- Updated `Table` component to use the new row components based on grouping state.
- Added `grouping` state and `onGroupingChange` handler in `TableProvider`.
- Set default grouping to 'newsvalue' in `AssignmentsList`, `EventsList`, and `PlanningList` components.
> feat(table): add optional grouping to table rows

- src/components/Link/lib/handleLink.ts
- src/navigation/lib/navigationReducer.tsx
Fixed the handling of onDocumentCreated callback in handleLink and navigationReducer. Moved the history.pushState call to the end of the handleLink function and updated the navigationReducer to set the content and active viewId directly.
> fix(navigation): onDocumentCreated handling

- src/components/Table/GroupedRowsHeader.tsx
- src/lib/index/wires.ts
- src/types/@tanstack/react-table.tsx
- src/views/Wires/WiresList.tsx
- src/views/Wires/WiresListColumns.tsx
- Change grouping from 'issued' to 'created' in WiresList
- Update sorting logic in wires.ts to use 'created' field
- Add display function for groupingMeta in GroupedRowsHeader
- Modify column definitions in WiresListColumns to handle new grouping
> fix(wires): update grouping and sorting logic

- src/components/View/Root.tsx
Children are not using flex attributes and it makes the header size not right sometimes.
> Remove flex on View root as it is unnecessary and mess with header height

- package-lock.json
- package.json
- shared/getLocaleData.ts
- src/components/AssignmentTime/ExecutionTimeMenu.tsx
- src/components/DataItem/TimeDisplay.tsx
- src/components/Datepicker.tsx
- src/components/Table/Items/Time.tsx
- src/components/Version/components/index.tsx
- src/contexts/RegistryProvider.tsx
- src/defaults/locale.ts
- src/types/index.ts
- src/views/Approvals/DoneMarkedBy.tsx
- src/views/Assignments/AssignmentColumns.tsx
- src/views/Event/components/EventTime.tsx
- src/views/EventsOverview/EventsGridColumn.tsx
- src/views/EventsOverview/EventsListColumns.tsx
- src/views/EventsOverview/index.tsx
- src/views/Factboxes/FactboxColumns.tsx
- src/views/Latest/index.tsx
- src/views/PlanningOverview/PlanningGridColumn.tsx
- src/views/SearchOverview/SearchColumns.tsx
Introduce dynamic locale handling by integrating `getLocaleData` and refactoring components to use `locale.code.full`. Added `LocaleData` type and default locale configuration. Updated `RegistryProvider` to initialize locale dynamically.
BREAKING CHANGE: Locale is now an object with `code` and `module` properties instead of a string.
Initial bundle size
```
Before:
3,123.01 kB │ gzip: 811.84 kB
After:
2,512.68 kB │ gzip: 694.25 kB
Reduction: 
-19.54%     | -14.48%
```
> feat(locale): implement dynamic locale handling

- src/components/Header/index.tsx
- src/defaults/assignmentTypes.tsx
- src/defaults/templates/editorialInfoDocumentTemplate.ts
- src/defaults/templates/index.ts
- src/defaults/templates/lib/getDeliverableType.ts
- src/defaults/templates/lib/getTemplateFromDeliverable.ts
- src/defaults/templates/lib/getTemplateFromView.ts
- src/defaults/workflowSpecification.tsx
- src/lib/createYItem.ts
- src/views/Editor/EditorHeader.tsx
- src/views/Planning/components/Assignment.tsx
- src/views/Planning/components/AssignmentRow.tsx
- src/views/Planning/components/AssignmentTable.tsx
- src/views/Planning/components/CreateDeliverablePrompt.tsx
- Introduced `editorial-info` as a new deliverable type.
- Added `editorialInfoDocumentTemplate` for generating templates.
- Updated workflow specifications for `editorial-info`.
- Enhanced `Assignment` and `AssignmentRow` components to handle `editorial-info`.
- Modified `CreateDeliverablePrompt` to support `editorial-info`.
- Renamed `getTemplate` to `getTemplateFromView` for clarity.
- Added `getDeliverableType` and `getTemplateFromDeliverable` utilities.
> feat(editorial-info): add support for new deliverable type

- __tests__/stateless.test.ts
- shared/stateless.ts
- src-srv/api/documents/[id]/index.ts
- src-srv/api/snapshot/[id]/index.ts
- src-srv/lib/assertContext.ts
- src-srv/lib/errorHandler.ts
- src-srv/routes.ts
- src-srv/utils/CollaborationServer.ts
- src-srv/utils/extensions/Auth.ts
- src-srv/utils/extensions/Snapshot.ts
- src/components/Duplicate/index.tsx
- src/components/Move/Prompt.tsx
- src/views/Event/index.tsx
- src/views/Factbox/index.tsx
- src/views/Flash/lib/createFlash.tsx
- src/views/Planning/index.tsx
- src/views/Wire/lib/createArticle.tsx
Introduced a new `GET` endpoint at `/api/snapshot/[id]` to handle document snapshots. The endpoint validates session context, checks document existence in the cache, and interacts with the collaboration server to create snapshots. Added robust error handling and context validation to ensure reliability.
BREAKING CHANGE: Requires `agent` property in context for snapshot operations.
> feat(api): add snapshot endpoint for document snapshots

- src/views/Editor/components/ReadOnly.tsx
Steps to reproduce in stage:
1. Open up a read-only article from a Planning view.
2. Slide open the MetaSheet from the header.
3. Close the MetaSheet, as well as the article.
4. Back in the Planning view, open up the same article again.
5. 💥
> fix: add argument to swr call to prevent fetching stale data

- src/views/Wire/WireViewContent.tsx
When deleting the slug, the field is removed. Only when a planning is selected.
> fix(Wire): dont hide slug component when empty

- shared/Index.ts
- src/hooks/index/useDocuments/index.ts
- src/hooks/index/useDocuments/lib/fetch.ts
- src/hooks/index/useDocuments/schemas/factbox.ts
- src/views/Event/components/DuplicatesTable.tsx
- src/views/EventsOverview/EventsList.tsx
- src/views/Factboxes/FactboxList.tsx
- src/views/PlanningOverview/PlanningList.tsx
- src/views/PrintArticles/PrintFlows.tsx
- src/views/Wires/WiresList.tsx
- Introduced `subscribe` option in `useDocumentsFetchOptions` to enable subscription-based updates.
- Updated `Index` class to handle subscriptions and polling for updates.
- Modified `useDocuments` hook to manage subscriptions and poll for updates when enabled.
- Enhanced `fetch` function to set subscriptions from the server response.
- Updated various views to enable subscription support where applicable.
- Refactored `factbox` schema to improve type safety and export fields.
- Improved error handling and added user notifications for fetch and polling failures.
> feat: add subscription support to document fetching

- src-srv/api/snapshot/[id]/index.ts
- src-srv/routes.ts
- src-srv/utils/CollaborationServer.ts
- src/hooks/useWorkflowStatus.tsx
- src/lib/snapshot.ts
- src/views/Editor/index.tsx
- Introduced a `force` query parameter to the snapshot API to allow forced snapshots even when no changes are detected.
- Updated `snapshotDocument` method in `CollaborationServer` to handle `force` parameter and ensure proper hash usage.
- Enhanced `useWorkflowStatus` hook to utilize the new snapshot response for version updates.
- Refactored `snapshot` utility to support the `force` parameter and return detailed response data.
- Adjusted `Editor` view to correctly handle version logic based on workflow status.
These changes improve snapshot functionality and ensure accurate versioning in workflows.
```
> fix(WorkflowStatus): do snapshot before setting status

- shared/Index.ts
- src/hooks/index/useDocuments/index.ts
- Only subscribe to the first page when paginating
- Updated `pollSubscription` method in `Index` class to include an optional `abortSignal` parameter for better control over polling.
- Enhanced `useDocuments` hook to use an `AbortController` for managing long polling subscriptions.
- Introduced `AbortError` class to handle abort-specific errors during polling.
- Refactored polling logic into a separate `pollSubscriptions` function for improved readability and reusability.
- Adjusted default values for `maxWaitMs` and `batchDelayMs` in `pollSubscription` method.
These changes improve the robustness and maintainability of the subscription polling mechanism.
> fix(useDocuments): subscribe with pagination, add abort signal support

- shared/User.ts
- shared/types/errors.ts
- src/components/UserMessagesReceiver.tsx
- Introduced `AbortSignal` to `pollMessages` method in `User` class to allow cancellation of polling requests.
- Created a new `AbortError` class to handle aborted requests gracefully.
- Updated `UserMessagesReceiver` to use `AbortController` for managing polling lifecycle and cleanup.
- Added event listener for `beforeunload` to abort polling on page unload.
- Enhanced error handling to differentiate between abort errors and other exceptions.
> feat(user): add abort signal support for message polling

- shared/transformations/newsdoc/core/factbox.ts
- Updated `transformFactbox` to wrap content in a `core/factbox/body` block with a unique ID and class.
- Modified `revertFactbox` to extract and process the `core/factbox/body` block instead of all children except the title.
> fix(factbox): add body wrapper for factbox content

- src/views/Editor/EditorHeader.tsx
- src/views/Editor/index.tsx
When in readOnly mode and displayed version isn't the latest, instead of StatusMenu show button to go-to-latest.
Problem apparent with: https://github.com/ttab/elephant-chrome/pull/1379
> fix(editor): add button to open latest version from read-only

- src/views/Planning/components/PlanDate.tsx
Update PlanDate component to set both start and end date fields when the date is changed. This ensures that the end date is always synchronized with the start date, improving consistency in planning item data. Also, use the user's time zone when creating new dates for better accuracy.
> fix(planning/event): sync end date with start date on change

- src/hooks/useWorkflowStatus.tsx
Ensure that when neither snapshotResponse.version nor documentStatus?.version is available, the hook falls back to newStatus.version. This fixes status updates for wires where previous logic failed to provide a valid version.
> fix(workflow): fallback to newStatus.version for wires

- src/components/Assignees.tsx
- src/components/AssignmentTime/index.tsx
- src/components/DataItem/AssignmentType.tsx
- src/components/DataItem/AssignmentVisibility.tsx
- src/components/DataItem/SluglineEditable.tsx
- src/components/Description.tsx
- src/components/DocumentStatus/StatusButton.tsx
- src/components/DocumentStatus/StatusMenu.tsx
- src/components/DocumentStatus/StatusOptions.tsx
- src/components/Form/Content.tsx
- src/components/Form/Group.tsx
- src/components/Form/Root.tsx
- src/components/Form/Title.tsx
- src/components/Move/index.tsx
- src/components/Newsvalue.tsx
- src/components/Section.tsx
- src/components/Story.tsx
- src/components/Title.tsx
- src/components/ui/TextBox.tsx
- src/components/ui/Textbox/TextboxEditable.tsx
- src/components/ui/Textbox/TextboxRoot.tsx
- src/hooks/useWorkflowStatus.tsx
- src/hooks/useYValue.tsx
- src/views/Planning/components/Assignment.tsx
- src/views/Planning/components/AssignmentRow.tsx
- src/views/Planning/components/AssignmentTable.tsx
- src/views/Planning/components/PlanDate.tsx
- src/views/Planning/components/PlanningHeader.tsx
- src/views/Planning/index.tsx
Add `onChange` prop to form components and propagate it through the form tree, allowing child components to notify the root form of unsaved changes. Update relevant components (e.g., Title, Description, Assignment, AssignmentTable, etc.) to call `onChange` when their state changes. Integrate this with the workflow status menu to show "Save changes" when there are unsaved changes. Use root.changed for tracking. This enables accurate UI feedback for unsaved changes across the planning view.
TODO: Implement onChange in Events and Factbox as well
> feat(form): propagate onChange for unsaved changes tracking

- __tests__/noConsecutiveEmptyParagraphs.test.tsx
- shared/transformations/yjsNewsDoc.ts
Removes consecutive empty paragraphs for text documents (article, flash and editorial-info). Do not touch anything but paragraphs (role is empty).
> Remove excessive empty paragraphs on snapshotting text documents

- __tests__/getStatusFromMeta.test.ts
- shared/Baboon.ts
- shared/Index.ts
- shared/Repository.ts
- shared/Spellchecker.ts
- shared/User.ts
- shared/Workflow.ts
- src-srv/lib/errorHandler.ts
- src-srv/utils/assertAuthenticatedUser.ts
- src/components/Version/index.tsx
Set the `sendJson: true` option for all TwirpFetchTransport client instances to ensure JSON payloads are sent correctly. This affects Baboon, Index, Repository, Spellchecker, User, and Workflow shared clients. Also, improve type safety in assertAuthenticatedUser and isOnStatelessPayload functions, and add explicit type casting in Version component for document fetch responses.
> fix(TwirpFetchTransport): set sendJson for TwirpFetchTransport clients

- shared/Baboon.ts
- shared/Index.ts
- shared/Repository.ts
- shared/Spellchecker.ts
- shared/User.ts
- shared/Workflow.ts
Add `jsonOptions: { ignoreUnknownFields: true }` to all TwirpFetchTransport client initializations in shared modules. This ensures that clients will gracefully handle extra fields in JSON responses, improving forward compatibility and robustness against backend changes.
> feat: ignore unknown fields in Twirp clients

- src-srv/utils/CollaborationServer.ts
Add UUID validation to prevent repository calls with invalid UUIDs, which are likely userTracker documents. This avoids unnecessary repository requests and potential errors.
> fix: validate UUIDs before repository operations

- src/defaults/templates/eventDocumentTemplate.ts
- src/views/Event/components/EventTime.tsx
- src/views/Event/index.tsx
Set event dateGranularity to 'time' in the template and default fullDay to false in EventTime menu. Also adjust EventViewContent footer padding for better alignment. These changes improve event time handling and UI consistency.
> Default should be todays date and time. End time should be set to same as start time.
Was already, current date, current time, for both start and end
> When changing the start time to a later time than end time, the end time should be set to same as start time.
I would argue that this isn't transparent to the user, now we have validation if start is after end -  that is more transparent I would say. :shrug:
> fix(event): update time granularity and UI defaults

- src/components/Category.tsx
- src/components/ContentSource.tsx
- src/views/Editor/components/MetaSheet.tsx
- src/views/Editor/components/ReadOnly.tsx
Introduce a new ContentSource component for selecting and displaying non-TT sources in the MetaSheet. Remove the old single content source display and update the ReadOnly view to support multiple sources. This improves source management and clarity for editorial metadata.
> feat(metasheet): add ContentSource combobox

- src-srv/utils/CollaborationServer.ts
- src/views/Event/index.tsx
Enhance the EventViewContent form to support document status handling ('usable', 'done', or undefined) on submit. Updated the submit handler to accept a status parameter and send it with the stateless message. Modified the form footer to provide buttons for different submission statuses, improving user control over event publishing workflow.
Based on: https://github.com/ttab/elephant-chrome/pull/1429
> feat(event): add status handling to event submission

- src/views/Planning/index.tsx
Refactored the planning form submission to support multiple document statuses: 'usable', 'done', and undefined. Updated the submit handler to accept a status parameter and adjusted the form footer to provide distinct buttons for "Spara", "Intern", and "Publicera", each triggering the appropriate status. This enhances user control over document publishing states.
Based on: https://github.com/ttab/elephant-chrome/pull/1429
> feat(planning): add status handling to planning submission

- src/hooks/useQuery.tsx
Refactor useQuery to handle query parameters more reliably for inactive views. Instead of replacing the pathname, now extracts the query string from the correct path segment, ensuring accurate parsing regardless of the view's active state. This prevents issues when the pathname differs between views and improves consistency in parameter retrieval.
> fix(hooks): improve query param parsing for inactive views

- src/views/Latest/hooks/useLatest.tsx
- src/views/Latest/index.tsx
Refactor Latest view to fetch and merge articles, flashes, and editorial info from the last 24 hours. Add logic to display "TT-FLASH" as the slugline for flash documents based on their URI.
> feat(latest): add flash and editorial-info types to view

- __tests__/createFlash.test.ts
- package-lock.json
- package.json
- src/components/Form/Submit.tsx
- src/defaults/documentStatuses.tsx
- src/defaults/workflowSpecification.tsx
- src/views/Flash/FlashViewContent.tsx
- src/views/Flash/lib/createFlash.tsx
- Introduced `CreateFlashDocumentStatus` type to handle different flash document statuses: 'usable', 'done', or undefined.
- Refactored `FlashViewContent` to use a prompt config array for handling send, save, and done prompts, reducing code duplication.
- Added tertiary button/action for "Godkänn flash" (approve flash).
- Updated `createFlash` to show different toast messages based on document status and improved error handling with user feedback.
- Updated form submit logic to require explicit button roles and handle tertiary actions.
- Updated newsvalue for created planning to 5
> feat(flash): add document status and tertiary action

- shared/Repository.ts
- src-srv/api/snapshot/[id]/index.ts
- src-srv/utils/CollaborationServer.ts
- src-srv/utils/extensions/Snapshot.ts
- Refactored Snapshot extension to handle debouncing and snapshot logic internally, removing the need to pass a snapshot function in config.
- Updated snapshot logic to call the API endpoint directly with proper authorization and user headers.
- Improved authentication in snapshot API route to support both session and header-based tokens and user info.
- Removed optimistic locking in Repository update payloads for snapshots.
- Cleaned up unused types and streamlined debounce handling.
> feat(snapshot): refactor snapshot extension and API auth

- __tests__/getStatusFromMeta.test.ts
- src/components/DocumentStatus/StatusMenu.tsx
- src/hooks/useWorkflowStatus.tsx
- src/lib/getStatusFromMeta.ts
Extend getStatusFromMeta to accept an isWorkflow flag, allowing it to return the workflowState for workflow documents and workflowCheckpoint for non-workflow documents. Update useWorkflowStatus and StatusMenu to pass the correct isWorkflow value based on document type. Enhance tests to cover new logic and ensure isWorkflow does not affect non-workflow results.
> feat(status): support workflow state/checkpoint in getStatusFromMeta

- src/hooks/index/useAssignments.tsx
- src/views/Approvals/index.tsx
Extend the Approvals view and useAssignments hook to include 'editorial-info' types and listen for 'core/editorial-info' repository events. This enables handling of editorial info assignments and ensures real-time updates when related events occur.
> fix(approvals): support editorial-info assignments

- src/components/Story.tsx
- src/views/Editor/components/MetaSheet.tsx
Introduce an `asSubject` prop to the Story component to allow specifying the `rel` attribute as 'subject' or 'story' based on context. Update MetaSheet to use Story with `asSubject` for correct API behavior.
> fix(story): add asSubject prop to Story component

- src/hooks/useWorkflowStatus.tsx
- src/lib/snapshot.ts
Add error handling in the snapshot function to return a status code and message when an error occurs, instead of throwing. Update useWorkflowStatus to check for error status in the snapshot response and exit early if an error is detected. This prevents further processing on failed snapshot attempts and improves error feedback.
> fix(snapshot): handle and return error status from snapshot

- src/views/PrintEditor/LayoutBox.tsx
- src/views/PrintEditor/PrintEditorHeader.tsx
- src/views/PrintEditor/components/Additionals.tsx
- src/views/PrintEditor/components/Layouts.tsx
- src/views/PrintEditor/components/Position.tsx
- src/views/PrintEditor/index.tsx
Add `isChanged` prop to EditorHeader and propagate change tracking through LayoutBox, Layouts, Position, and Additionals components. Introduce `onChange` callbacks to update a Yjs-backed `changed` flag when edits occur. This enables UI elements to reflect unsaved changes state, improving user awareness of document modifications.
> fix(print-editor): track unsaved changes in editor UI

- src-srv/api/snapshot/[id]/index.ts
- src-srv/routes.ts
- src-srv/utils/CollaborationServer.ts
- src-srv/utils/createSnapshot.ts
- src/components/Table/index.tsx
- src/hooks/useWorkflowStatus.tsx
- src/lib/snapshot.ts
- src/views/Planning/components/AssignmentRow.tsx
- src/views/Planning/components/AssignmentTable.tsx
- src/views/Planning/index.tsx
- src/views/Wires/components/PreviewSheet.tsx
- Add support for sending `status` and `cause` as query params and payload in the snapshot API POST endpoint.
- Update backend and utility functions to handle new parameters and propagate them through snapshot and document update flows.
- Refactor `useWorkflowStatus` to allow direct wire status updates and pass status/cause to snapshot.
- Update Table and PreviewSheet components to use new wire status logic, including keyboard shortcuts and status dropdown.
- Update snapshot utility to POST with Yjs update and new options.
> refactor(snapshot): support status/cause in snapshot API and wire status

- src-srv/api/documents/[id]/index.ts
- src/views/Editor/components/MetaSheet.tsx
- src/views/Wires/components/PreviewSheet.tsx
Fix MetaSheet to display properties, tags, byline, actions, and content source fields only for documents of type 'core/article'. This prevents irrelevant fields from showing for other document types. Also, ensure PreviewSheet passes readOnly and readOnlyVersion props to MetaSheet for correct rendering in preview mode. Additionally, fix a navigation handler to check for wire existence before updating document status.
Additional change: When version param is provided, don't get document from cache.
> fix(metasheet): show applicable fields for each documentType

- src-srv/api/documents/[id]/snapshot.ts
The cache check prevents changing status on documents not in redis cache (i.e) read only published articles
> Removed unecessary cache check

- src-srv/api/urls/index.ts
- src/lib/getServerUrls.ts
It's more efficient to communicate directly to internal services rather than through the public domain and load balancer that clients have to go through.
This adds support for specifying a separate `[SERVICE]_PUBLIC_URL` that will be preferred over the normal URL by the "/api/urls" endpoint.
Also made the `getServerurls()` method more "data driven". Probably less typescript friendly, which I guess was the main driver for the previous method, but gives us the benefit of better error messages when a server URL is missing.
> add support for a separation of cluster-internal and public URLs

- src-srv/api/signout/index.ts
- src-srv/index.ts
- src-srv/utils/CollaborationServer.ts
- src-srv/utils/assertAuthenticatedUser.ts
- src-srv/utils/authConfig.ts
- src-srv/utils/authSession.ts
- src-srv/utils/extensions/Auth.ts
Also making sure that we capture the actual errors when token refresh fails.
> make less assumptions about OpenID endpoints, get rid of globals

- shared/transformations/newsdoc/core/table-rows.ts
Previously, empty rows in tables were not handled, which could lead to unexpected behavior or display issues. This change ensures that empty rows are returned as 'core/table/row/error' objects, allowing them to be displayed as 'unknown object' and improving robustness.
> fix(table): handle empty table rows as error objects

- src/hooks/useNavigationKeys.tsx
Permit alt+left and alt+right key navigation even when focus is in an editor view. This enables custom view navigation shortcuts without browser interference, while preserving default arrow key behavior for text editing.
> fix(nav): allow alt+arrow navigation in with editor focus

- src/components/Header/Datechanger.tsx
- src/components/Link/lib/handleLink.ts
- src/components/Table/GroupedRows.tsx
- src/components/Table/Row.tsx
- src/components/Table/index.tsx
- src/hooks/useOpenDocuments.tsx
- Fix link handling to avoid duplicate query strings in path
- Remove unused `activeId` prop from `GroupedRows` and related logic
- Use `openDocuments` to determine selected rows in `Row` component
- Update row styling to use `data-state=selected` for selection
- Add 'PrintEditor' to open document names in `useOpenDocuments`
- Refactor `DateChanger` for better date handling and link props
> fix(navigation): apply query to correct view when keepfocus is used
