- package-lock.json
- package.json
- src/lib/initializeNavigationState.tsx
- tailwind.config.ts
Waiting for: https://github.com/ttab/elephant-ui/pull/14
> fix: use resolved preset for settings

- src-srv/index.ts
- src-srv/utils/RedisCache.ts
A little bit to fast, missed these types and params :slightly_frowning_face:
> fix: params and types

- package-lock.json
- package.json
- src/components/AppHeader/index.tsx
Use with: https://github.com/ttab/elephant-ui/pull/19
> fix: use sheet close button

- src/components/DataItem/StatusIndicator.tsx
- src/views/PlanningOverview/PlanningTable/Columns/Priority.tsx
- src/views/PlanningOverview/index.tsx
I'm unable to find a good way to specify column widths, this pr solves a ui bug, but we still need to figure out how to tighten up the columns. Especially the static content ones with fixed widths.
> fix: overlapping elements

- src/components/Link/lib/handleReset.ts
- src/components/ViewHeader/ViewHeader.tsx
- src/views/PlanningOverview/PlanningHeader/Datechanger.tsx
Reset by clicking title or icon in ViewHeader or by keyboard shortcut alt+shift+<view number> this combination is used due to its resemblance to alt+<number> which is browser default to switch tabs
> fix(Navigation): reset navigation

- src/components/ui/TextBox.tsx
- src/views/Planning/components/Assignment.tsx
- src/views/Planning/components/PlanDescription.tsx
- src/views/Planning/components/PlanTitle.tsx
- src/views/Planning/index.tsx
also changed internal icon in textbox
> Improved lineheight, paddings and margins on textboxes

- src/components/View/ViewHeader/Title.tsx
- src/navigation/index.tsx
- src/navigation/lib/initializeNavigationState.tsx
- src/views/Error/index.tsx
- src/views/index.tsx
Works only on simple cases for now. Should be generalized later on.
> Added simple error view, loaded on trying to load non existant view

- src/components/DataItem/SluglineEditable.tsx
- src/components/ui/TextBox.tsx
- src/views/Planning/components/Assignment.tsx
- src/views/Planning/components/AssignmentTable.tsx
- src/views/Planning/components/PlanDescription.tsx
- src/views/Planning/components/PlanTitle.tsx
- src/views/Planning/index.tsx
- src/views/PlanningOverview/PlanningHeader/Datepicker.tsx
Many small tweaks to make the UI feel more polished
> Improved planning UI

- __tests__/__snapshots__/transform-document.test.ts.snap
- __tests__/data/article-newsdoc.ts
- package-lock.json
- package.json
- src-srv/utils/transformations/newsdoc/tt/visual.ts
- src/views/Editor/index.tsx
> feat: use tt/visual

- src/defaults/visibilityStatuses.tsx
Seems to have worked, so i just renamed the labels
> fix: rename visibilityStatuses

- src/components/ui/TextBox.tsx
Most of the issue seemed to be solved, just a minor adjustment of top padding
> fix: padding top

- src/components/Title.tsx
- src/views/Planning/components/Assignment.tsx
- Added `path` and `className` props to `Title` component.
- Integrated `handleValidation` function in `Assignment` component.
- Replaced `TextBox` with `Title` in `Assignment` component.
- Added validation logic to ensure required fields are filled.
> feat: add validation Assignment creation form

- __tests__/useQuery.test.tsx
- src/components/Header/Datechanger.tsx
- src/components/ValidationAlert.tsx
- src/hooks/useQuery.tsx
- src/plugins/Factboxes/index.tsx
- src/plugins/ImageSearch/index.tsx
- src/views/Assignments/index.tsx
- src/views/Editor/index.tsx
- src/views/Event/index.tsx
- src/views/EventsOverview/index.tsx
- src/views/Factbox/index.tsx
- src/views/Flash/index.tsx
- src/views/Planning/index.tsx
- src/views/PlanningOverview/index.tsx
- Implemented useQuery hook to manage URL query parameters.
- Added unit tests for useQuery hook to ensure functionality.
> feat: add useQuery hook with tests

- src/views/Planning/components/AssignmentRow.tsx
- Added Pen icon to AssignmentRow for editing
- Moved onClick event to AssignmentRowContent
> feat(AssignmentRow): add click to open pen to edit

- __tests__/transform-unordered-list.test.ts
- src-srv/utils/transformations/lib/toString.ts
- src-srv/utils/transformations/newsdoc/core/factbox.ts
- src-srv/utils/transformations/newsdoc/core/index.ts
- src-srv/utils/transformations/newsdoc/core/unorderedList.ts
- src-srv/utils/transformations/newsdoc/index.ts
- src-srv/utils/transformations/newsdoc/tt/visual.ts
- Implemented transformation and reversion for unordered lists
- Added unit tests for unordered list transformations
- Refactored toString utility function for reuse
> feat(transformations): add unordered list support

- src/components/DataItem/Slugline.tsx
Replaced the Button component with the Badge component in the StaticSluglineByValue function to improve UI consistency and accessibility.
> fix(slugline): replace Button with Badge component

- .env.tpl
- package-lock.json
- package.json
- src/App.tsx
- src/AppContent.tsx
- src/views/Error/index.tsx
- Added @grafana/faro-react to dependencies in package.json
- Initialized Faro in App.tsx with environment variables
- Wrapped components in FaroErrorBoundary in ViewWrapper
- Updated Error component to display error messages
> feat: integrate @grafana/faro-react for error tracking

- src/components/Avatar.tsx
- src/components/AvatarGroup.tsx
* Added the contain-layout class to the avatarGroupVariants in
* AvatarGroup.tsx to improve layout containment and styling.
> fix(AvatarGroup): add contain-layout class for better styling

- src/components/Editor/ContentMenu.tsx
- src/components/Editor/ContextMenu.tsx
- src/components/View/Footer.tsx
- src/components/View/index.tsx
- src/views/Editor/index.tsx
- Added new Footer component to View
- Updated ContentMenu and ContextMenu with z-index
> fix(editor): focused fixes, menus and footer

- src/components/Modal/ModalSheet.tsx
- src/components/Table/index.tsx
- src/views/Wires/WiresListColumns.tsx
- src/views/Wires/index.tsx
* Remove full editor view
* Click shows preview
* Click outside hides preview
* Group +/-
* Show full time
> fix: improve modal handling and preview functionality

- src/components/Link/lib/handleLink.ts
- src/components/Table/index.tsx
- src/hooks/useLink.tsx
- Added keepFocus boolean to LinkClick interface and handleLink function
- Updated Table component to pass keepFocus based on space key event
- Ensured viewId is retained if keepFocus is true
> feat(handlelink): add keepFocus

- src/contexts/RepositoryEventsProvider.tsx
- src/hooks/index/lib/assignments/fetch.ts
- src/hooks/index/lib/assignments/filter.ts
- src/hooks/index/lib/assignments/structure.ts
- src/hooks/index/useAssignments.tsx
- Moved fetch logic to `fetch.ts` to handle assignment fetching
- Added `filter.ts` to filter assignments based on statuses
- Created `structure.ts` to categorize assignments into time slots
- Updated `useAssignments.tsx` to use the new modular functions
> feat(useAssignments): separate fetch, filter, and structure

- package-lock.json
- package.json
- src/components/View/ViewHeader/CreateDocumentDialog.tsx
- src/components/View/ViewHeader/Root.tsx
depending on: https://github.com/ttab/elephant-ui/pull/574
> fix(dialog): prepare for max-height

- src/defaults/templates/flashDocumentTemplate.ts
- src/views/Flash/FlashViewContent.tsx
- src/views/Flash/addFlashToPlanning.ts
Some misunderstandings straightened out.
Flash shouldn't have: newsvalue, since it's implied, neither should it have an author (it's on the assignment)
> fix: validate flash, no newsvalue, no author

- src/components/DataItem/AssignmentType.tsx
based from: https://github.com/ttab/elephant-chrome/pull/1214
> fix: use select and file text icon

- src/components/Commands/Items/TextFilter.tsx
- src/components/Filter/index.tsx
- src/contexts/TableProvider.tsx
- src/views/Assignments/index.tsx
- src/views/EventsOverview/index.tsx
- src/views/PlanningOverview/index.tsx
* Added `handleInputChange` function in `Filter` component to manage global filter updates.
* Improved keyboard navigation for `Command` component, handling `Enter` and `Backspace` keys more effectively.
* Introduced `globalFilter` state in `TableProvider` and updated `onGlobalFilterChange` to sync with query parameters.
* Updated `Assignments`, `EventsOverview`, and `PlanningOverview` views to include `globalFilter` in their initial state.
These changes improve the user experience and consistency of the
filtering functionality across the application.
> fix(filter): enhance global filter handling and UX

- src/views/Editor/components/Notes/index.tsx
- src/views/Editor/index.tsx
* Added confirmation prompts for removing and changing note types in the Editor Notes component.
* Updated labels for note roles to improve clarity.
* Made Notes sticky.
> fix(notes): add confirmation prompts for note actions

- src-srv/utils/CollaborationServer.ts
- src-srv/utils/extensions/OpenDocuments.ts
Should now work correctly with many redis instances and correctly handle startups/crashes et al.
> Refactored open documents tracking into a new Hocuspocus extension.

- src/components/Move/Prompt.tsx
- src/components/Move/index.tsx
- src/components/Prompt.tsx
- src/components/ui/DotMenu.tsx
- src/views/EventsOverview/EventsListColumns.tsx
- src/views/Planning/components/AssignmentRow.tsx
- src/views/Planning/components/CreateDeliverablePrompt.tsx
- Ensured `onPrimary` in AssignmentRow prevents default and stops propagation.
> fix(AssignmentRow): improve dropdown menu and assignment row UX

- src/views/Planning/components/AssignmentRow.tsx
> fix(AssignmentRow): make readonly open up next to origin, instead of

- src/views/Event/components/PlanningTable.tsx
- src/views/Planning/index.tsx
after being added to related planning items table
> fix: newly created planning items should be visible immediately

- src/hooks/index/useAssignments.tsx
- Extended `useRepositoryEvents` to include `core/article` and `core/article+meta` event types.
- Updated assignment matching logic to consider `_deliverableId` for event UUIDs.
This improves event handling.
> fix(useAssignments): extend event handling and logging

- shared/Repository.ts
- src/hooks/index/lib/assignments/fetchAssignments.ts
- src/views/Latest/index.tsx
Replace `useAssignments` with `useDocuments` for fetching data in `Latest` view.
> fix(latest): enhance document handling and UI

- src-srv/utils/extensions/Snapshot.ts
Enhance the Snapshot extension by introducing stricter context validation using `assertContext` and UUID checks for document names. Refactor `onDisconnect` to provide better error handling and clearer error messages. This improves robustness and prevents invalid operations during document storage and disconnection events.
> fix(snapshot): improve context validation and error handling

- src/components/View/ViewHeader/ViewDialogClose.tsx
- src/views/Event/components/PlanningTable.tsx
Compromise to keep to as few changes as possible. I think this is good enough.
> fix(modal): on prompt at a time, fix padding child modal

- __tests__/transform-tv-listing.test.ts
- package-lock.json
- package.json
- shared/transformations/newsdoc/tt/tvListing.ts
- src/defaults/contentMenuLabels.ts
- src/views/PrintEditor/index.tsx
* Use tv-listing plugin from @ttab/textbit-plugins.
Companion PR: https://github.com/ttab/textbit-plugins/pull/424
> Feat print add tvlisting

- src/hooks/index/lib/assignments/fetchAssignments.ts
Update assignment filtering logic to ensure only assignments with a planning date or start date matching the given date are included.
> fix(fetchAssignments): filter assignments by correct date

- src/views/Approvals/ApprovalsCard.tsx
- src/views/Approvals/AuthorNames.tsx
- src/views/Approvals/DoneMarkedBy.tsx
- src/views/Approvals/index.tsx
- src/views/Approvals/makeAuthorNames.tsx
Refined logic for outputting names on Approval view cards
> Approvals card byline improvements
